--CRIANDO UM USUARIO
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER lucas IDENTIFIED BY lucas DEFAULT TABLESPACE USERS;
-- DANDO ACESSO TOTAL AO USUARIO CRIADO
GRANT CONNECT, RESOURCE TO LUCAS;
-- ADICIONANDO UMA COTA ILIMITADA DE TAMANHO DA TABLESPACE (AREA DE TRABALHO)
ALTER USER lucas QUOTA UNLIMITED ON USERS;

-- CRIANDO OUTRO USUARIO
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER cursoplsql2 IDENTIFIED BY cursoplsql2 DEFAULT TABLESPACE USERS;
GRANT connect, resource TO cursoplsql2;
ALTER USER cursoplsql2 QUOTA UNLIMITED ON USERS;