-- TIPOS DE TABELAS CRIADAS

create table TB_CLIENTES(
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO NUMBER(15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1));

create table TB_VENDEDORES(
    MATRICULA VARCHAR2(5),
    NOME VARCHAR2(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER);

create table cliente(
    cli_cod integer CONSTRAINT pk_cliente_cli_cod Primary Key,
    cli_nome varchar(30),
    cli_ativo number(2) default 1,
    cli_data_nasc date);

CREATE TABLE TB_CLIENTES(
CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(2),
CEP VARCHAR(8),
IDADE INT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA NUMBER(1));

CREATE TABLE TB_PRODUTOS(
PRODUTO VARCHAR (20),
NOME VARCHAR (150),
EMBALAGEM VARCHAR (50),
TAMANHO VARCHAR (50),
SABOR VARCHAR (50),
PRECO_LISTA FLOAT);

CREATE TABLE Cliente (
    cli_id integer  NOT NULL,
    nome varchar2(255)  NOT NULL,
    CONSTRAINT Cliente_pk PRIMARY KEY (cli_id)
) ;

CREATE TABLE Peca (
    pec_id integer  NOT NULL,
    descricao varchar2(255)  NOT NULL,
    valor number(18,2)  NOT NULL,
    quantidade integer  NOT NULL,
    CONSTRAINT Peca_pk PRIMARY KEY (pec_id)
) ;

CREATE TABLE Pedido (
    ped_id integer  NOT NULL,
    data date  NOT NULL,
    valor number(18,2)  NOT NULL,
    Cliente_cli_id integer  NOT NULL,
    CONSTRAINT Pedido_pk PRIMARY KEY (ped_id)
) ;

CREATE TABLE Pedido_Peca (
    Pedido_ped_id integer  NOT NULL,
    Peca_pec_id integer  NOT NULL,
    quantidade integer  NULL,
    valor number(18,2)  NULL,
    CONSTRAINT Pedido_Peca_pk PRIMARY KEY (Pedido_ped_id,Peca_pec_id)
) ;

CREATE TABLE PRODUTOS(
    CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(50)NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT NULL,
    
    PRIMARY KEY (CODIGO));
    
CREATE TABLE VENDEDORES(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100)NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADIMISSAO DATE NULL,
    FERIAS INTEGER NULL,
    
    PRIMARY KEY (MATRICULA));
    
CREATE TABLE TABELA_DE_VENDAS(
    NUMERO VARCHAR2(5) NOT NULL,
    DATA_VENDA DATE NULL,
    CPF VARCHAR2(11) NOT NULL,
    MATRICULA VARCHAR2(5) NOT NULL,
    IMPOSTO FLOAT NULL,
    
    PRIMARY KEY (NUMERO));    
    
CREATE TABLE ITENS_NOTAS(
    NUMERO VARCHAR2(5) NOT NULL,
    CODIGO VARCHAR2(10) NOT NULL,
    QUANTIDADE INTEGER NULL,
    PRECO FLOAT NULL,
    
    PRIMARY KEY (NUMERO, CODIGO));


-- ALTER TABLE
ALTER TABLE TB_CLIENTES ADD DATA_NASCIMENTO DATE;
ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF);
ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY (PRODUTO);
ALTER TABLE Pedido ADD CONSTRAINT Pedido_Cliente FOREIGN KEY (Cliente_cli_id) REFERENCES Cliente (cli_id);
ALTER TABLE Pedido_Peca ADD CONSTRAINT Pedido_Peca_Peca FOREIGN KEY (Peca_pec_id) REFERENCES Peca (pec_id);
ALTER TABLE Pedido_Peca ADD CONSTRAINT Pedido_Peca_Pedido FOREIGN KEY (Pedido_ped_id) REFERENCES Pedido (ped_id);
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);
ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);
ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;
ALTER TABLE TABELA_DE_VENDAS RENAME TO NOTAS;

-- CREATE SEQUENCE

CREATE SEQUENCE Cliente_seq
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

CREATE SEQUENCE Peca_seq
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

CREATE SEQUENCE Pedido_seq
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- INSERT INTO

INSERT INTO cliente (cli_cod, cli_nome, cli_ativo, cli_data_nasc) VALUES (1,'Joao',1,'15/05/1996');

INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','','Agua Santa','Rio de Janeiro','RJ','22000000',TO_DATE('2000-02-12','YYYY-MM-DD'),18,'M',100000,200000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('2600586709','Cesar Teixeira','Rua Conde de Bonfim','','Tijuca','Rio de Janeiro','RJ','22020001',TO_DATE('2000-03-12','YYYY-MM-DD'),18,'M',120000,220000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('95939180787','Fabio Carvalho','R. dos Jacarandas da Peninsula','','Barra da Tijuca','Rio de Janeiro','RJ','22002020',TO_DATE('1992-01-05','YYYY-MM-DD'),16,'M',90000,180000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('9283760794','Edson Meilelles','R. Pinto de Azevedo','','Cidade Nova','Rio de Janeiro','RJ','22002002',TO_DATE('1995-10-07','YYYY-MM-DD'),22,'M',150000,250000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('7771579779','Marcelo Mattos','R. Eduardo Luis Lopes','','Bras','Sao Paulo','SP','88202912',TO_DATE('1992-03-25','YYYY-MM-DD'),25,'M',120000,200000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5576228758','Petra Oliveira','R. Benicio de Abreu','','Lapa','Sao Paulo','SP','88192029',TO_DATE('1995-11-14','YYYY-MM-DD'),22,'F',70000,160000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8502682733','Valdeci da Silva','R. Srg. edison de Oliveira','','Jardins','Sao Paulo','SP','82122020',TO_DATE('1995-10-07','YYYY-MM-DD'),22,'M',110000,190000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('1471156710','Erica Carvalho','R. Iriquitia','','Jardins','Sao Paulo','SP','80012212',TO_DATE('1990-09-01','YYYY-MM-DD'),27,'F',170000,245000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('3623344710','Marcos Nougeuira','Av. Pastor Martin Luther King Junior','','Inhauma','Rio de Janeiro','RJ','22002012',TO_DATE('1995-01-13','YYYY-MM-DD'),23,'M',110000,220000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('50534475787','Abel Silva ','Rua Humaita','','Humaita','Rio de Janeiro','RJ','22000212',TO_DATE('1995-09-11','YYYY-MM-DD'),22,'M',170000,260000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5840119709','Gabriel Araujo','R. Manuel de Oliveira','','Santo Amaro','Sao Paulo','SP','80010221',TO_DATE('1985-03-16','YYYY-MM-DD'),32,'M',140000,210000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('94387575700','Walber Lontra','R. Cel. Almeida','','Piedade','Rio de Janeiro','RJ','22000201',TO_DATE('1989-06-20','YYYY-MM-DD'),28,'M',60000,120000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8719655770','Carlos Eduardo','Av. Gen. Guedes da Fontoura','','Jardins','Sao Paulo','SP','81192002',TO_DATE('1983-12-20','YYYY-MM-DD'),34,'M',200000,240000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5648641702','Paulo Cesar Mattos','Rua Helio Beltrao','','Tijuca','Rio de Janeiro','RJ','21002020',TO_DATE('1991-08-30','YYYY-MM-DD'),26,'M',120000,220000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('492472718','Eduardo Jorge','R. Volta Grande','','Tijuca','Rio de Janeiro','RJ','22012002',TO_DATE('1994-07-19','YYYY-MM-DD'),23,'M',75000,95000,1);

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1040107','Light - 350 ml - Melancia','Lata','350 ml','Melancia',4.555);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.309);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.51);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1088126','Linha Citros - 1 Litro - Limao','PET','1 Litro','Limao',7.004);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('544931','Frescor do Verao - 350 ml - Limao','Lata','350 ml','Limao',2.4595);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1078680','Frescor do Verao - 470 ml - Manga','Garrafa','470 ml','Manga',5.1795);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1042712','Linha Citros - 700 ml - Limao','Garrafa','700 ml','Limao',4.904);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('788975','Pedacos de Frutas - 1,5 Litros - Maca','PET','1,5 Litros','Maca',18.011);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002767','Videira do Campo - 700 ml - Cereja/Maca','Garrafa','700 ml','Cereja/Maca',8.41);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('231776','Festival de Sabores - 700 ml - Acai','Garrafa','700 ml','Acai',13.312);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('479745','Clean - 470 ml - Laranja','Garrafa','470 ml','Laranja',3.768);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1051518','Frescor do Verao - 470 ml - Limao','Garrafa','470 ml','Limao',3.2995);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1101035','Linha Refrescante - 1 Litro - Morango/Limao','PET','1 Litro','Morango/Limao',9.0105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('229900','Pedacos de Frutas - 350 ml - Maca','Lata','350 ml','Maca',4.211);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1086543','Linha Refrescante - 1 Litro - Manga','PET','1 Litro','Manga',11.0105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('695594','Festival de Sabores - 1,5 Litros - Acai','PET','1,5 Litros','Acai',28.512);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('838819','Clean - 1,5 Litros - Laranja','PET','1,5 Litros','Laranja',12.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('326779','Linha Refrescante - 1,5 Litros - Manga','PET','1,5 Litros','Manga',16.5105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('520380','Pedacos de Frutas - 1 Litro - Maca','PET','1 Litro','Maca',12.011);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1041119','Linha Citros - 700 ml - Lima/Limao','Garrafa','700 ml','Lima/Limao',4.904);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('243083','Festival de Sabores - 1,5 Litros - Maracuja','PET','1,5 Litros','Maracuja',10.512);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('394479','Sabor da Montanha - 700 ml - Cereja','Garrafa','700 ml','Cereja',8.409);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('746596','Light - 1,5 Litros - Melancia','PET','1,5 Litros','Melancia',19.505);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('773912','Clean - 1 Litro - Laranja','PET','1 Litro','Laranja',8.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('826490','Linha Refrescante - 700 ml - Morango/Limao','Garrafa','700 ml','Morango/Limao',6.3105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('723457','Festival de Sabores - 700 ml - Maracuja','Garrafa','700 ml','Maracuja',4.912);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('812829','Clean - 350 ml - Laranja','Lata','350 ml','Laranja',2.808);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('290478','Videira do Campo - 350 ml - Melancia','Lata','350 ml','Melancia',4.56);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','700 ml','Morango',7.709);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('235653','Frescor do Verao - 350 ml - Manga','Lata','350 ml','Manga',3.8595);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002334','Linha Citros - 1 Litro - Lima/Limao','PET','1 Litro','Lima/Limao',7.004);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1013793','Videira do Campo - 2 Litros - Cereja/Maca','PET','2 Litros','Cereja/Maca',24.01);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1096818','Linha Refrescante - 700 ml - Manga','Garrafa','700 ml','Manga',7.7105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1022450','Festival de Sabores - 2 Litros - Acai','PET','2 Litros','Acai',38.012);