-- DANDO PERMISSÃO AO USUARIO user_app EXECUTAR AS PROCEDURES
GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO user_app;
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO user_app;
GRANT EXECUTE ON EXCLUIR_CLIENTE TO user_app;
GRANT EXECUTE ON INCLUIR_CLIENTE TO user_app;

-- DANDO PERMISSÃO AO USUARIO user_app REALIZAR O SELECT NA TABELA
GRANT SELECT ON CLIENTE TO user_app;

-- CRIANDO UM SINONIMO AS PROCEDURES E TABELA, PARA FACILITAR A CHAMADA DO MÉTODO
CREATE PUBLIC SYNONYM ADD_CLIENTE FOR USER_DEV.INCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM ATUALIZAR_CLI_SEG_MERCADO FOR USER_DEV.ATUALIZAR_CLI_SEG_MERCADO;
CREATE PUBLIC SYNONYM ATUALIZAR_FATURAMENTO_PREVISTO FOR USER_DEV.ATUALIZAR_FATURAMENTO_PREVISTO;
CREATE PUBLIC SYNONYM EXCLUIR_CLIENTE FOR USER_DEV.EXCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM CLIENTE FOR USER_DEV.CLIENTE;